config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  # root 'posts#index'
  root 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :list, presence: true
  validates :movie, presence: true
  validates_uniqueness_of :list_id, { scope: :movie_id}
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    list = List.find(params[:list_id])

    @bookmark = list.bookmarks.new(bookmark_params)

    if @bookmark.save
      redirect_to list_path(list)
    else
      @list = list
      @bookmarks = list.bookmarks.where.not(updated_at: nil)
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show]
  def index
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks.sort_by{ |bookmark| bookmark.updated_at }
    @movies = @list.movies
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    list = List.new(params_list)
    if list.save
      redirect_to list_path(list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def params_list
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="nav-bar">
  <%= link_to "ADD NEW LIST  ?????", new_list_path, class: "btn btn-outline-primary" %>
</div>

<div class="banner"  >
<h1>WELCOME TO THE MOVIE SHOW</h1>
</div>


<div class="nav-bar">
  <h2>My list</h2>
  <%= link_to "ADD NEW LIST  ?????", new_list_path, class: "btn btn-outline-primary" %>
</div>
<div class="lists-list">
  <% @lists.each do |list| %>
  <div>
    <div class="list-item">
     <%= link_to list.name, list_path(list.id), class: "text-decoration-none color-white" %> 
    </div>
  </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
<div class="form-inputs">
  <%= f.input :name %>
</div>

<div class="form-actions">
  <%= f.button :submit %> 
</div>
<% end%>

app/views/lists/show.html.erb
<div class="banner"  >
  <h1><%= @list.name %></h1>
</div>

<div class="new-bookmark-form">
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <h3> Add a new movie to this list 🦾</h3>

    <div class="form-item">
      <%= f.input :movie_id, collection: Movie.all, label: "Select Movie" %> 
      <%= f.input :comment %>  
    </div>

    <div class="form-button">
      <%= f.button :submit, class: "btn btn-outline-primary w-100" %> 
    </div>
  <% end %>
</div>

<%= link_to "BACK TO THE LISTS LIST", lists_path, class: "btn btn-outline-primary m-4 " %>

<div class="cards">
  <% @bookmarks.reverse.each do |bookmark| %>
    <% movie = Movie.find(bookmark.movie_id) %>
    <div class="card">
      <img src="<%= movie.poster_url %>" alt="<%= movie.title %>">
      <h2><%= "#{movie.title} • #{movie.rating}⭐" %></h2>
      <h6><%= movie.overview %></h6>
      <p><%= bookmark.comment %></p>
      <%= link_to 'delete', bookmark_path(bookmark.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure???" }, class: "btn btn-outline-danger" %>
    </div>
  <% end %>
</div>